### ISSUE TITLE
HTTP authentication needs a new version pushed

### ISSUE THREAD

**Issue by dannyfallon** [simplabs/ember-cli-deploy-webhooks#13]
It's been 24 days since HTTP authentication support was added but there hasn't been a push of a new version to the npm repository - could you publish one? I'd hate to have to host a fork privately for this, it's a very useful feature :smile:

**Comment by dannyfallon** [comment]
Thankfully it's just basic auth I need so I've added a custom `Authorization` header and base64-encoded the auth for now.

**Comment by marcoow** [comment]
@dannyfallon: we'll push a new version (under a new name, see #11) later today!

**Comment by LevelbossMike** [comment]
@dannyfallon We just published a new version under a new name (to make it clearer for what this plugin can be used to do in your deployment pipeline) https://www.npmjs.com/package/ember-cli-deploy-webhooks

**Comment by dannyfallon** [comment]
Thank you both :+1:
