### ISSUE TITLE
Docs are not available

### ISSUE THREAD

**Issue by eredi93** [simplabs/ember-cli-deploy-webhooks#16]
I'm trying to exit the deployment if the webhook didn't respond with the right status code.
The docs for the plugin are not available, when i click on the README link i get a 404.

**Comment by LevelbossMike** [comment]
Thanks for pointing this out. The references to the plugin documentation are meant to refer to the [overall documentation](http://ember-cli-deploy.com/docs/v0.6.x/plugins-overview/) of what an ember-cli-deploy-plugin actually is though.

The documentation for this plugin can be found [here](https://github.com/simplabs/ember-cli-deploy-webhooks/blob/master/README.md).

**Comment by eredi93** [comment]
Thx for getting back to me 😊
