### ISSUE TITLE
QUESTION:  discord setup 

### ISSUE THREAD

**Issue by danielspaniel** [simplabs/ember-cli-deploy-webhooks#30]
This is a neat idea. Me like. Is it pretty staightforward to make it so I can push notification to discord channel. 
 You have setup for slack and bugsnag, and not sure how easy that would be?

**Comment by marcoow** [comment]
Sure, you can use this with Discord as well. The Slack and Bugsnag example in the README are really just examples - this is a generic library that works with **any** webhooks - if you know the URL, method and potentially headers for Discord, ember-cli-deploy-webhooks should be able to call that simply by reading the configuration for it.
