### ISSUE TITLE
Rough eta on a 1.0

### ISSUE THREAD

**Issue by Pezmc** [simplabs/ember-cli-deploy-webhooks#31]
Hi there,

Thanks for doing the work to update to 1.0-beta and merging the open PR's.
Do you have a rough idea how long you'll be in "beta", or it is stable enough I shouldn't worry and can go ahead and use this in production?

Thanks again!

**Comment by marcoow** [comment]
This is stable - don't worry about using it in production. I think we'll update a few dependencies which might technically be considered breaking changes before 1.0.0 but don't worry about using it.
